sudo: false
language: node_js
node_js:
  - "8"
  - "6"
env:
  - CODECOV_TOKEN=f467855e-3e4b-4920-bc74-c57fcde6466b
cache:
  npm: true
  directories:
    - "node_modules"
script:
  - npm run test
  - npm run codecov
